# Pandas
- Solve short hands-on challenges to perfect your data manipulation skills.
- https://www.kaggle.com/learn/pandas

## 6.- Exercise: Renaming and Combining
- Data comes in from many sources. Help it all make sense together.
- Columns names, index names, or other naming conventions to change.
- Combine data from multiple Dataframes and/or Series.

In [1]:
import pandas as pd

print('pd.__version__:', pd.__version__)

# pd.set_option('display.max_rows', 5)

pd.__version__: 1.5.3

In [2]:
reviews = pd.read_csv('Red.csv')
reviews.head(2)

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.0,2011
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.5,2017

In [6]:
## Add a twitter_region column !
reviews['twitter_region'] = '@' +  reviews.Region
reviews.head()

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,twitter_region
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011,@Pomerol
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017,@Lirac
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015,@Toscana
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019,@Bardolino
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016,@Carnuntum

In [5]:
# ## Add rows with NaN values - Not in this case...
# display(reviews.head(2))
# print(len(reviews))

# ndf_row1 = pd.DataFrame({'Name': 'Name1', 'Country': np.nan, 'Region': 'Reg1',
#                          'Winery': 'Win1', 'Rating': 1, 'NumberOfRatings': 101,
#                          'Price': 10.1, 'Year': 2021, 'twitter_region': '@Reg1'}, index=[0])
# revs = pd.concat([reviews, ndf_row1]).reset_index(drop=True)    # concat at the end
# ndf_row2 = pd.DataFrame({'Name': 'Name2', 'Country': np.nan, 'Region': 'Reg2',
#                          'Winery': 'Win2', 'Rating': 2, 'NumberOfRatings': 202,
#                          'Price': 20., 'Year': 2022, 'twitter_region': '@Reg2'}, index=[0])
# revs = pd.concat([ndf_row2, revs]).reset_index(drop=True)    # concat at the beginning and in the same df

# lst_row3 = ['Name3', np.nan, 'Reg3', 'Win3', np.nan, 303, np.nan,2023, '@Reg3']
# revs.loc[3423.5] = lst_row3                         # make index float and insert in .5
# print('revs.index.dtype now:', revs.index.dtype)
# revs = revs.sort_index().reset_index(drop=True)     # return index to int and add
# revs

#### 1.- region_1 and region_2 are pretty uninformative names for locale columns in the dataset. Create a copy of reviews with these columns renamed to region and locale, respectively.

In [7]:
# Ragion x district and Winery wine_cellar
renamed = reviews.rename(columns={'Region': 'district', 'Winery': 'wine_cellar'})
renamed.head()

,Name,Country,district,wine_cellar,Rating,NumberOfRatings,Price,Year,twitter_region
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011,@Pomerol
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017,@Lirac
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015,@Toscana
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019,@Bardolino
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016,@Carnuntum

#### 2.- Set the index name in the dataset to wines.

In [12]:
# reindexed = reviews.rename_axis('wines', axis='rows')
reindexed = reviews.rename_axis('wines', axis='rows').rename_axis('Cols_name', axis='columns')
reindexed.head()

Cols_name,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,twitter_region
wines,,,,,,,,,
0,Pomerol 2011,France,Pomerol,Château La Providence,4.2,100,95.00,2011,@Pomerol
1,Lirac 2017,France,Lirac,Château Mont-Redon,4.3,100,15.50,2017,@Lirac
2,Erta e China Rosso di Toscana 2015,Italy,Toscana,Renzo Masi,3.9,100,7.45,2015,@Toscana
3,Bardolino 2019,Italy,Bardolino,Cavalchina,3.5,100,8.72,2019,@Bardolino
4,Ried Scheibner Pinot Noir 2016,Austria,Carnuntum,Markowitsch,3.9,100,29.15,2016,@Carnuntum

#### 3.- The Things on Reddit dataset includes product links from a selection of top-ranked forums ("subreddits") on reddit.com. Run the cell below to load a dataframe of products mentioned on the /r/gaming subreddit and another dataframe for products mentioned on the r//movies subreddit.

In [14]:
# Create two new df from original loaded 
# Make two news df based on two country of origen.
rev_nz = reviews.loc[reviews.Country == 'New Zealand']
display(rev_nz.head(2))
rev_bz = reviews.loc[reviews.Country == 'Brazil']
display(rev_bz.head(2))

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,twitter_region
6,Marion's Vineyard Pinot Noir 2016,New Zealand,Wairarapa,Schubert,4.0,100,43.87,2016,@Wairarapa
78,Pinot Noir 2016,New Zealand,Marlborough,Clos Henri Vineyard,3.9,102,27.78,2016,@Marlborough

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,twitter_region
23,Virtus Tannat 2013,Brazil,Serra Gaúcha,Monte Paschoal,2.9,100,6.77,2013,@Serra Gaúcha
66,Fausto Tannat 2015,Brazil,Serra Gaúcha,Pizzato,3.6,1012,11.35,2015,@Serra Gaúcha

In [17]:
# Create a DataFrame of products mentioned on either subreddit. (wines reviewed on either df)
combined_wines = pd.concat([rev_bz, rev_nz])
display(combined_wines.head(2), combined_wines.tail(2))

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,twitter_region
23,Virtus Tannat 2013,Brazil,Serra Gaúcha,Monte Paschoal,2.9,100,6.77,2013,@Serra Gaúcha
66,Fausto Tannat 2015,Brazil,Serra Gaúcha,Pizzato,3.6,1012,11.35,2015,@Serra Gaúcha

,Name,Country,Region,Winery,Rating,NumberOfRatings,Price,Year,twitter_region
8622,Reserve Pinot Noir 2017,New Zealand,Marlborough,Villa Maria,3.8,98,25.79,2017,@Marlborough
8644,Private Bin Merlot - Cabernet Sauvignon 2016,New Zealand,Hawke's Bay,Villa Maria,3.4,99,12.60,2016,@Hawke's Bay

#### 4.- The Powerlifting Database dataset on Kaggle includes one CSV table for powerlifting meets and a separate one for powerlifting competitors. Run the cell below to load these datasets into dataframes:

In [18]:
# NumberOfRatings common values to join
left = rev_bz.set_index(['NumberOfRatings'])
right = rev_nz.set_index(['NumberOfRatings'])

left.join(right, lsuffix='_B', rsuffix='_N')

,Name_B,Country_B,Region_B,Winery_B,Rating_B,Price_B,Year_B,twitter_region_B,Name_N,Country_N,Region_N,Winery_N,Rating_N,Price_N,Year_N,twitter_region_N
NumberOfRatings,,,,,,,,,,,,,,,,
31,Family Vineyards Tannat 2015,Brazil,Rio Grande do Sul,Miolo,3.5,11.19,2015,@Rio Grande do Sul,Premium Merlot 2014,New Zealand,Hawke's Bay,Saint Clair,3.7,12.95,2014,@Hawke's Bay
31,Family Vineyards Tannat 2015,Brazil,Rio Grande do Sul,Miolo,3.5,11.19,2015,@Rio Grande do Sul,Pinot Noir 2017,New Zealand,Wairarapa,Johner Estate,3.7,13.02,2017,@Wairarapa
62,Family Vineyards Merlot 2015,Brazil,Rio Grande do Sul,Miolo,3.0,9.90,2015,@Rio Grande do Sul,Pinot Noir 2017,New Zealand,Central Otago,Elephant Hill,3.6,25.90,2017,@Central Otago
80,Seival Tannat 2012,Brazil,Campanha,Miolo,3.6,11.50,2012,@Campanha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Reserva Merlot 2016,Brazil,Serra Gaúcha,Don Guerino,3.7,12.62,2016,@Serra Gaúcha,Calvert Pinot Noir 2017,New Zealand,Central Otago,Felton Road,4.2,67.90,2017,@Central Otago
90,Intenso Tannat 2013,Brazil,Campanha,Salton,3.3,9.95,2013,@Campanha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,Reserva Cabernet Sauvignon 2012,Brazil,Serra Gaúcha,Don Guerino,3.3,12.62,2012,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,Virtus Tannat 2013,Brazil,Serra Gaúcha,Monte Paschoal,2.9,6.77,2013,@Serra Gaúcha,Marion's Vineyard Pinot Noir 2016,New Zealand,Wairarapa,Schubert,4.0,43.87,2016,@Wairarapa
103,Merlot Reserva 2008,Brazil,Vale dos Vinhedos,Pizzato,3.2,15.90,2008,@Vale dos Vinhedos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Reserva Cabernet Sauvignon 2013,Brazil,Serra Gaúcha,Don Guerino,3.3,12.62,2013,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
128,Dedicato Tannat 2013,Brazil,Serra Gaúcha,Monte Paschoal,3.9,15.55,2013,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
146,Reserva Tannat 2014,Brazil,Serra Gaúcha,Don Guerino,3.5,13.60,2014,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147,Da'Divas Pinot Noir 2010,Brazil,Encruzilhada do Sul,Lidio Carraro,3.2,14.50,2010,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,Cabernet Sauvignon Reserva 2012,Brazil,Vale dos Vinhedos,Pizzato,3.6,14.50,2012,@Vale dos Vinhedos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,Virtus Merlot 2015,Brazil,Serra Gaúcha,Monte Paschoal,3.0,6.77,2015,@Serra Gaúcha,Private Bin Merlot - Cabernet Sauvignon 2012,New Zealand,Hawke's Bay,Villa Maria,3.5,10.03,2012,@Hawke's Bay
186,Family Vineyards Pinot Noir 2015,Brazil,Rio Grande do Sul,Miolo,3.2,9.90,2015,@Rio Grande do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,Identidade Gran Terroir Corte 2013,Brazil,Rio Grande do Sul,Casa Valduga,4.0,24.90,2013,@Rio Grande do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
233,Gran Cave Merlot 2005,Brazil,Serra Gaúcha,Boscato,3.8,37.50,2005,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
255,Fausto Merlot 2012,Brazil,Serra Gaúcha,Pizzato,3.0,11.45,2012,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,Elos Cabernet Sauvignon - Malbec 2009,Brazil,Encruzilhada do Sul,Lidio Carraro,3.4,29.19,2009,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,Reserva Teroldego 2014,Brazil,Serra Gaúcha,Don Guerino,3.7,14.57,2014,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
326,Tannat (Grande Vindima) 2010,Brazil,Encruzilhada do Sul,Lidio Carraro,4.0,73.06,2010,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,Agnus Malbec 2015,Brazil,Encruzilhada do Sul,Lidio Carraro,3.4,12.62,2015,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
395,Flowers Tinto Suave 2014,Brazil,Serra Gaúcha,Salton,3.0,6.90,2014,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
406,Agnus Cabernet Sauvignon 2012,Brazil,Encruzilhada do Sul,Lidio Carraro,3.2,11.65,2012,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
443,Flowers Tinto Seco 2013,Brazil,Serra Gaúcha,Salton,3.0,6.95,2013,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479,Da'Divas Tempranillo 2012,Brazil,Encruzilhada do Sul,Lidio Carraro,3.5,14.57,2012,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,Reserva Teroldego 2016,Brazil,Serra Gaúcha,Don Guerino,3.8,14.57,2016,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
524,Elos Cabernet Sauvignon - Malbec 2011,Brazil,Encruzilhada do Sul,Lidio Carraro,3.7,29.19,2011,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
538,Fausto Merlot 2015,Brazil,Serra Gaúcha,Pizzato,3.5,11.45,2015,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
701,Da'Divas Tempranillo 2016,Brazil,Encruzilhada do Sul,Lidio Carraro,3.6,16.52,2016,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
720,Da'Divas Pinot Noir 2012,Brazil,Encruzilhada do Sul,Lidio Carraro,3.3,14.57,2012,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
722,Agnus Merlot 2011,Brazil,Encruzilhada do Sul,Lidio Carraro,3.2,11.65,2011,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
819,Quorum (Grande Vindima) 2006,Brazil,Vale dos Vinhedos,Lidio Carraro,3.9,45.77,2006,@Vale dos Vinhedos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
829,Fausto Merlot 2016,Brazil,Serra Gaúcha,Pizzato,3.5,11.45,2016,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
902,Merlot (Grande Vindima) 2008,Brazil,Encruzilhada do Sul,Lidio Carraro,3.9,45.77,2008,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,Elos Touriga Nacional - Tannat 2012,Brazil,Encruzilhada do Sul,Lidio Carraro,3.9,29.19,2012,@Encruzilhada do Sul,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1012,Fausto Tannat 2015,Brazil,Serra Gaúcha,Pizzato,3.6,11.35,2015,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1627,Quorum (Grande Vindima) 2008,Brazil,Vale dos Vinhedos,Lidio Carraro,4.0,45.77,2008,@Vale dos Vinhedos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2066,Talento 2012,Brazil,Serra Gaúcha,Salton,3.8,16.72,2012,@Serra Gaúcha,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4846,Lote 43 Cabernet Sauvignon - Merlot 2012,Brazil,Vale dos Vinhedos,Miolo,4.2,22.90,2012,@Vale dos Vinhedos,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
### correct one:
# powerlifting_combined = powerlifting_meets.set_index("MeetID").join(powerlifting_competitors.set_index("MeetID"))

## remember more exercises with:
''' .join(), .merge(), .pivot()'''